baseurl = "https://www.fabiocolinelli.com/"
title = "Fabio Colinelli"
theme = "hugo-creative-portfolio-theme"
publishDir = "docs"
languageCode = "it-it"
# Enable comments by entering your Disqus shortname
disqusShortname = ""
# Enable Google Analytics by entering your tracking code
googleAnalytics = ""

[params]
  # Style options: default (pink), blue, green, pink, red, sea, violet
  # Use custom.css for your custom styling
  style = "default"
  description = "Personal website of Fabio Colinelli"
  copyright = "&copy;2020 Fabio Colinelli"
  sidebarAbout = [
    "I am a creative illustrator and graphic designer with more than 30 years of experience.",
    "Currently based in Forlimpopoli (Italy)."
  ]
  # Contact page
     # Since this template is static, the contact form uses www.formspree.io as a
     # proxy. The form makes a POST request to their servers to send the actual
     # email. Visitors can send up to a 1000 emails each month for free.
     #
     # What you need to do for the setup?
     #
     # - set your email address under 'email' below
     # - upload the generated site to your server
     # - send a dummy email yourself to confirm your account
     # - click the confirm link in the email from www.formspree.io
     # - you're done. Happy mailing!
  email = "fabio.pixel.colinelli@gmail.com"

    # Optional Matomo analytics (formerly piwik)
      # [params.analytics.matomo]
      #  URL = "https://stats.example.com"
      #  ID = "42"
      #  # Track all subdomains with "*.example.com" (Optional)
      #  domain = "www.example.com"
      #  # Optional integrity check hash
      #  hash = ""

  # Nav links in the side bar

  [[params.navlinks]]
  name = "I RIVISTI"
  url = "rivisti/"
  home = true
  
  [[params.navlinks]]
  name = "Hollywood & C."
  url = "hollywood/"
    
  [[params.navlinks]]
  name = "Statue a fumetti"
  url = "statue/"
    
  [[params.navlinks]]
  name = "Fumetti & C."
  url = "fumetti/"
  
   [[params.navlinks]]
  name = "Mostre ed esposizioni"
  url = "mostre/"
   
  [[params.navlinks]]
  name = "Merchandise"
  url = "merchandise/"
  
  [[params.navlinks]]
  name = "Press"
  url = "pres/"
  
  [[params.navlinks]]
  name = "About"
  url = "about/"

  [params.social]
  #facebook      = "https://www.facebook.com/fabio.p.colinelli"
  facebook      = "https://www.facebook.com/ziopixel"
  email         = "fabio.pixel.colinelli@gmail.com"
  #twitter       = "https://twitter.com/fabiocolinelli"
  #linkedin      = "full profile url in linkedin"
  #stackoverflow = "full profile url in stackoverflow"
  instagram     = "https://www.instagram.com/zio_pixel/"
  #github        = "full profile url in github"
  #youtube       = "full profile url in youtube"
  #whatsapp      = "wa.me service link"
