baseURL = "https://www.fabiocolinelli.com/"
languageCode = "en-us"
title = "www.fabiocolinelli.com"
theme = "hugo-split-theme"
publishDir = "docs"

disableKinds = ["section", "taxonomy", "taxonomyTerm", "RSS", "sitemap"]

# Enter your tracking code to enable Google Analytics
googleAnalytics = ""

# Copyright
copyright = "&copy;2019 Fabio Colinelli"

[params]

  # Metadata for search engines and social sharing
  author = "Fabio Colinelli"
  description = "Split is a centrally-divided layout for a professional online presence with a big image or video left with alongside content."
  shareImage = "images/bo.png"
  twitterHandle = "onepagelove"

  # Favicon
  favicon = "favicon.ico"

  # Section - Visual
  [params.visual]

    # Image
    [params.visual.image]
      enable = true
      file = "face.jpg"
      position = "center center"

    # Video
    [params.visual.video]
      enable = false
      mute = true
      file = "videos/background.mp4"
      # youtubeId = "dk9uNWPP7EA"

  # Links
  #
  # Links List #1
  [[params.links]]
    [params.links.list1]
      heading = "Social"

      [[params.links.list1.link]]
        text = "Facebook"
        url = "https://www.facebook.com/fabio.p.colinelli"

  #    [[params.links.list1.link]]
  #      text = "Email"
  #      url = "#"

  #    [[params.links.list1.link]]
  #      text = "Newsletter"
  #      url = "#"

  # Links List #2
  [[params.links]]
    [params.links.list2]
      heading = "Portfolio"

      [[params.links.list2.link]]
        text = "Instagram"
        url = "https://www.instagram.com/zio_pixel/"

      #[[params.links.list2.link]]
      #  text = "Instagram"
      #  url = "https://www.instagram.com/zio_pixel/"

      #[[params.links.list2.link]]
      #  text = "Dribbble"
      #  url = "#"

  # Links List #3
  [[params.links]]
    [params.links.list3]
      heading = "Contact"

      [[params.links.list3.link]]
        text = "Mail"
        url = "mailto:pixel.ubuntu@gmailcom"

  #    [[params.links.list3.link]]
  #      text = "Link Two"
  #      url = "#"

  #    [[params.links.list3.link]]
  #      text = "Link Three"
  #      url = "#"

  # The original template is released under the Creative Commons Attribution 3.0 License.
  # Please keep the original attribution link when using for your own project.
  # If you'd like to use the template without the attribution, you can check out
  # the license option via the template author's website: https://onepagelove.com/split
